version: 2

updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Ignore auto-updates on SemVer major releases
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Ignore auto-updates on SemVer major releases
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "google-*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    allow:
      - dependency-type: development
      - dependency-type: production
    groups:
      requests-dependencies:
        patterns:
          - "requests"
          - "types-requests"
